spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        endereco-in:
          destination: endereco
          contentType: application/json
        endereco-out:
          destination: endereco
          contentType: application/json